#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

polybar -r &
bspc monitor -d 1 2 3 4 5 &

setxkbmap -rules evdev -model evdev -layout us -variant altgr-intl &
feh --bg-scale ~/Downloads/luci.png &
dunst &

bspc config border_width 2
bspc config window_gap 15

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle false

bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true
